### ISSUE TITLE
Crash during UpdatePFS message deserialization

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#158]
## Problem Definition

During startup the PFS crashes with the following message:

```
2019-03-12 10:42:32.030448 [critical ] Unhandled exception. Terminating the program...Please report this issue at https://github.com/raiden-network/raiden-services/issues [pathfinding_service.service]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 439, in _handle_response
    self.call(room._put_event, event)
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 387, in call
    return callback(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/matrix_client/room.py", line 308, in _put_event
    listener['callback'](self, event)
  File "/Users/paul/Projects/brainbot/raiden-services/src/raiden_libs/matrix.py", line 205, in _handle_message
    signer=message.sender,
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/structlog/stdlib.py", line 75, in warning
    return self._proxy_to_logger("warning", event, *args, **kw)
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/structlog/stdlib.py", line 119, in _proxy_to_logger
    method_name, event=event, **event_kw
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/structlog/_base.py", line 191, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/structlog/_base.py", line 151, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/structlog/dev.py", line 226, in __call__
    for key in sorted(event_dict.keys())
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/structlog/dev.py", line 226, in <genexpr>
    for key in sorted(event_dict.keys())
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/structlog/dev.py", line 171, in _repr
    return repr(inst)
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/messages.py", line 199, in __repr__
    msghash=pex(self.hash),
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/messages.py", line 184, in hash
    packed = self.packed()
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/messages.py", line 1854, in packed
    self.pack(packed)
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/messages.py", line 1860, in pack
    packed.token_network_address = self.token_network_address
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/encoding/format.py", line 150, in __setattr__
    raise ValueError(msg)
ValueError: value with length 42 for token_network_address is too big
Exiting...
```

**Comment by palango** [comment]
@Dominik1999 did you ever encounter this?

**Comment by Dominik1999** [comment]
No that error I have never seen
