### ISSUE TITLE
Monitoring Service can not claim reward - Error code -32016

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#181]
## Problem Definition

The monitoring serivice is not able to claim the reward. The transaction fails due to the below error code. 

## Actual Outcome
```
2019-03-20 13:08:05.344420 [error    ] Sending tx failed              [monitoring_service.handlers] err=ValueError({'code': -32016, 'message': 'The execution failed due to an exception.'})
Traceback (most recent call last):
  File "/home/pirate/PycharmProjects/Raiden_Services/raiden-services/src/monitoring_service/handlers.py", line 461, in action_claim_reward_triggered_event_handler
    ).transact({'from': context.ms_state.address})
  File "/home/pirate/PycharmProjects/Raiden_Services/venv/RaidenServices/lib/python3.7/site-packages/web3/contract.py", line 1156, in transact
    **self.kwargs
  File "/home/pirate/PycharmProjects/Raiden_Services/venv/RaidenServices/lib/python3.7/site-packages/web3/contract.py", line 1459, in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
  File "/home/pirate/PycharmProjects/Raiden_Services/venv/RaidenServices/lib/python3.7/site-packages/web3/eth.py", line 263, in sendTransaction
    get_buffered_gas_estimate(self.web3, transaction),
  File "/home/pirate/PycharmProjects/Raiden_Services/venv/RaidenServices/lib/python3.7/site-packages/web3/utils/transactions.py", line 84, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/home/pirate/PycharmProjects/Raiden_Services/venv/RaidenServices/lib/python3.7/site-packages/web3/eth.py", line 304, in estimateGas
    [transaction],
  File "/home/pirate/PycharmProjects/Raiden_Services/venv/RaidenServices/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32016, 'message': 'The execution failed due to an exception.'}
```

**Comment by palango** [comment]
A fix for not running claim was in #183
