### ISSUE TITLE
Uncatched exception: AssertionError: DB was created with receiver

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#409]
This should be handled:

```
onfig/raiden-monitoring-service/raiden-monitoring-service-42-0_15_0.db
Traceback (most recent call last):
  File "/home/krishna/Envs/raiden_services_env/bin/monitoring-service", line 11, in <module>
    load_entry_point('raiden-services', 'console_scripts', 'monitoring-service')()
  File "/home/krishna/Envs/raiden_services_env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/krishna/Envs/raiden_services_env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/krishna/Envs/raiden_services_env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/krishna/Envs/raiden_services_env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/krishna/raidenforked/raiden-services/src/raiden_libs/cli.py", line 169, in call_with_blockchain_info
    return callback(**params)
  File "/home/krishna/raidenforked/raiden-services/src/raiden_libs/cli.py", line 114, in call_with_common_options_initialized
    return func(**params)
  File "/home/krishna/raidenforked/raiden-services/src/monitoring_service/cli.py", line 57, in main
    min_reward=min_reward,
  File "/home/krishna/raidenforked/raiden-services/src/monitoring_service/service.py", line 89, in __init__
    sync_start_block=sync_start_block,
  File "/home/krishna/raidenforked/raiden-services/src/monitoring_service/database.py", line 260, in __init__
    sync_start_block=sync_start_block,
  File "/home/krishna/raidenforked/raiden-services/src/raiden_libs/database.py", line 77, in _setup
    self._check_settings(settings, hex_addresses)
  File "/home/krishna/raidenforked/raiden-services/src/raiden_libs/database.py", line 103, in _check_settings
    assert old == val, f"DB was created with {key}={old}, got {val}!"
AssertionError: DB was created with receiver=0x0A0b7Eb1D5EC00f3892D3c5A702471AaD007B7Ea, got 0x8f2e0940bEd6f90f1Cb14FEb37f045bB79C41b2d!

**Comment by karlb** [comment]
What is the intended result? Just a nicer error message?

**Comment by palango** [comment]
Yes, I think we shouldn't have uncatched exceptions.
