### ISSUE TITLE
Crash in PFS related to rate limiter

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#458]
## Problem Definition

@karlb Just saw this in our deployment

```
pfs-goerli_1            | 2019-07-16 09:38:12.429405 [info     ] Stopping Pathfinding Service... [__main__]
pfs-goerli_1            | Traceback (most recent call last):
pfs-goerli_1            |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
pfs-goerli_1            |     "__main__", mod_spec)
pfs-goerli_1            |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
pfs-goerli_1            |     exec(code, run_globals)
pfs-goerli_1            |   File "/services/src/pathfinding_service/cli.py", line 101, in <module>
pfs-goerli_1            |     main(auto_envvar_prefix="PFS")  # pragma: no cover
pfs-goerli_1            |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
pfs-goerli_1            |     return self.main(*args, **kwargs)
pfs-goerli_1            |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
pfs-goerli_1            |     rv = self.invoke(ctx)
pfs-goerli_1            |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
pfs-goerli_1            |     return ctx.invoke(self.callback, **ctx.params)
pfs-goerli_1            |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
pfs-goerli_1            |     return callback(*args, **kwargs)
pfs-goerli_1            |   File "/services/src/raiden_libs/cli.py", line 173, in call_with_blockchain_info
pfs-goerli_1            |     return callback(**params)
pfs-goerli_1            |   File "/services/src/raiden_libs/cli.py", line 118, in call_with_common_options_initialized
pfs-goerli_1            |     return func(**params)
pfs-goerli_1            |   File "/services/src/pathfinding_service/cli.py", line 75, in main
pfs-goerli_1            |     db_filename=state_db,
pfs-goerli_1            |   File "/services/src/pathfinding_service/service.py", line 99, in __init__
pfs-goerli_1            |     address_reachability_changed_callback=self.handle_reachability_change,
pfs-goerli_1            |   File "/services/src/raiden_libs/matrix.py", line 185, in __init__
pfs-goerli_1            |     self.rate_limiter(
pfs-goerli_1            | AttributeError: 'MatrixListener' object has no attribute 'rate_limiter'
```

**Comment by karlb** [comment]
That's trivial to fix (mostly a typo). But I'll have to make sure that this will be caught by a test in the future.

**Comment by karlb** [comment]
This is another case where the error has not been caught by mypy because MatrixListener inherits from `Greenlet`.

**Comment by palango** [comment]
> This is another case where the error has not been caught by mypy because MatrixListener inherits from `Greenlet`.

Does mypy ignore warnings in subclasses of `Greenlet`?

**Comment by karlb** [comment]
> Does mypy ignore warnings in subclasses of `Greenlet`?

At least anything related to missing attributes. There's probably a `__getattr__` or something similar in the `Greenlet` implementation that messes up the mypy checking. I've already stumbled across that multiple times. One of the reasons I like to banish gevent to as small parts of the code as possible.
