### ISSUE TITLE
Could not identify the intended function with name `firstBlockAllowedToMonitor`

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#511]
## Problem Definition
```
ms-goerli_1             | 2019-08-09 07:11:10.299418 [debug    ] Processing event               [monitoring_service.service] event_={'token_network_address': '0x070fEF2eA7cC30B91e5f0c650b78302B13a0E747', 'channel_identifier': 3, 'closing_participant': '0x7deA0108AB75a8CF373c02bdb237664A31fcf48B', 'block_number': 1036493, 'type_name': 'ReceiveChannelClosedEvent'}
ms-goerli_1             | Traceback (most recent call last):
ms-goerli_1             |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
ms-goerli_1             |     "__main__", mod_spec)
ms-goerli_1             |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
ms-goerli_1             |     exec(code, run_globals)
ms-goerli_1             |   File "/services/src/monitoring_service/cli.py", line 66, in <module>
ms-goerli_1             |     main(auto_envvar_prefix="MS")
ms-goerli_1             |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
ms-goerli_1             |     return self.main(*args, **kwargs)
ms-goerli_1             |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
ms-goerli_1             |     rv = self.invoke(ctx)
ms-goerli_1             |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
ms-goerli_1             |     return ctx.invoke(self.callback, **ctx.params)
ms-goerli_1             |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
ms-goerli_1             |     return callback(*args, **kwargs)
ms-goerli_1             |   File "/services/src/raiden_libs/cli.py", line 177, in call_with_blockchain_info
ms-goerli_1             |     return callback(**params)
ms-goerli_1             |   File "/services/src/raiden_libs/cli.py", line 122, in call_with_common_options_initialized
ms-goerli_1             |     return func(**params)
ms-goerli_1             |   File "/services/src/monitoring_service/cli.py", line 59, in main
ms-goerli_1             |     ms.start()
ms-goerli_1             |   File "/services/src/monitoring_service/service.py", line 126, in start
ms-goerli_1             |     self._process_new_blocks(last_block)
ms-goerli_1             |   File "/services/src/monitoring_service/service.py", line 160, in _process_new_blocks
ms-goerli_1             |     handle_event(event, self.context)
ms-goerli_1             |   File "/services/src/monitoring_service/service.py", line 56, in handle_event
ms-goerli_1             |     handler(event, context)
ms-goerli_1             |   File "/services/src/monitoring_service/handlers.py", line 131, in channel_closed_event_handler
ms-goerli_1             |     _first_allowed_block_to_monitor(event.token_network_address, channel, context) - 1
ms-goerli_1             |   File "/services/src/monitoring_service/handlers.py", line 96, in _first_allowed_block_to_monitor
ms-goerli_1             |     monitoring_service_address=context.ms_state.address,
ms-goerli_1             |   File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1033, in __call__
ms-goerli_1             |     clone._set_function_info()
ms-goerli_1             |   File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1042, in _set_function_info
ms-goerli_1             |     self.kwargs
ms-goerli_1             |   File "/usr/local/lib/python3.7/site-packages/web3/utils/contracts.py", line 128, in find_matching_fn_abi
ms-goerli_1             |     raise ValidationError(message)
ms-goerli_1             | web3.exceptions.ValidationError:
ms-goerli_1             | Could not identify the intended function with name `firstBlockAllowedToMonitor`, positional argument(s) of type `()` and keyword argument(s) of type `{'closed_at_block': <class 'int'>, 'settle_timeout': <class 'int'>, 'participant1': <class 'str'>, 'participant2': <class 'str'>, 'monitoring_service_address': <class 'bytes'>}`.
ms-goerli_1             | Found 1 function(s) with the name `firstBlockAllowedToMonitor`: ['firstBlockAllowedToMonitor(uint256,uint256,address,address,address)']
ms-goerli_1             | Function invocation failed due to no matching argument types.

**Comment by palango** [comment]
This is caused by https://github.com/raiden-network/raiden-services/pull/508/files#diff-7e601015b086be36d3e9eb6ed414424dR243

I just wonder why we don't have a test that runs that code path.
