### ISSUE TITLE
PFS crashes with unhandeled exception. Not able to resolve DNS

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#517]
## Problem Definition

```
2019-08-14 08:16:31.464993 [critical ] Unhandled exception. Terminating the program...Please report this issue at https://github.com/raiden-network/raiden-services/issues [raiden_libs.gevent_error_handler] 
2019-08-14 08:16:31.465505 [info     ] Stopping Pathfinding Service... [pathfinding_service.cli] 
Traceback (most recent call last):
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/gevent/_socketcommon.py", line 208, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/gevent/resolver/ares.py", line 230, in getaddrinfo
    return self._getaddrinfo(host, port, family, socktype, proto, flags)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/gevent/resolver/ares.py", line 191, in _getaddrinfo
    values = ares_values.get()
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/gevent/resolver/ares.py", line 357, in get
    raise self.error # pylint:disable=raising-bad-type
socket.gaierror: [Errno 4] ARES_ENOTFOUND: b'Domain name not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9a42020dd8>: Failed to establish a new connection: [Errno 4] ARES_ENOTFOUND: b'Domain name not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='geth.goerli.ethnodes.brainbot.com', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError("<urllib3.connection.HTTPConnection object at 0x7f9a42020dd8>: Failed to establish a new connection: [Errno 4] ARES_ENOTFOUND: b'Domain name not found'"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/bin/pathfinding-service", line 11, in <module>
    load_entry_point('raiden-services', 'console_scripts', 'pathfinding-service')()
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/raiden-services/src/raiden_libs/cli.py", line 177, in call_with_blockchain_info
    return callback(**params)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/raiden-services/src/raiden_libs/cli.py", line 122, in call_with_common_options_initialized
    return func(**params)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/raiden-services/src/pathfinding_service/cli.py", line 101, in main
    service.run()
  File "src/gevent/greenlet.py", line 718, in gevent._greenlet.Greenlet.run
  File "src/gevent/greenlet.py", line 706, in gevent._greenlet.Greenlet._report_error
  File "/home/pirate/PycharmProjects/ServicesRelease2000/raiden-services/src/raiden_libs/gevent_error_handler.py", line 24, in error_handler
    Hub.handle_system_error(self, etype, value)
  File "/home/pirate/PycharmProjects/ServicesRelease2000/venv/RaidenRelease2000/lib/python3.7/site-packages/gevent/hub.py", line 488, in handle_system_error
    self.parent.throw(type, value)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='geth.goerli.ethnodes.brainbot.com', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError("<urllib3.connection.HTTPConnection object at 0x7f9a42020dd8>: Failed to establish a new connection: [Errno 4] ARES_ENOTFOUND: b'Domain name not found'"))

``` 
## Expected Outcome
We should catch that error and terminate the pfs, after some retries, with a proper error message

**Comment by karlb** [comment]
This already does multiple retries (see `MaxRetryError`). While this is not a nice error, it does contain the reason (`Domain name not found`) and context (`host='geth.goerli.ethnodes.brainbot.com', port=8545`). So this can be considered good enough for people running the services for now.

Adding a better error message would involve adding a new exception in the transport and some additional greenlet error handling code. Let's focus on other things for now.
