### ISSUE TITLE
Check that MS is registered before sending tx

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#540]
Currently we don't check whether or not the MS address is registered in the service registry. This leads to failing transactions, that can be avoided.

**Comment by karlb** [comment]
This will already be checked during the gas estimation:
https://github.com/raiden-network/raiden-services/blob/fab27b4e4b31f6d7dfcd4737d2339b3652fe1b41/src/monitoring_service/handlers.py#L461-L465

So we won't waste any gas with the current approach. I assume this ticket is about checking for registration during the startup to fail early.

**Comment by palango** [comment]
I'm starting a scenario trying to reproduce this

**Comment by palango** [comment]
@karlb You were right. The error I saw is:
```
ms-kovan_1                    | 2019-09-18 11:56:16.667213 [debug    ] Processing event               [monitoring_service.service] event_={'token_network_address': '0x2FB01Ad0aC182Ba8A9E82a58E126C476555651f1', 'channel_identifier': 1, 'non_closing_participant': '0xfd9256718f4943580ce6f7a10F30FF1a4771a2e3', 'type_name': 'ActionMonitoringTriggeredEvent'}
ms-kovan_1                    | 2019-09-18 11:56:16.667834 [info     ] Triggering channel monitoring  [monitoring_service.handlers]
ms-kovan_1                    | 2019-09-18 11:56:16.775362 [error    ] Sending tx failed              [monitoring_service.handlers] err=ValueError({'code': -32016, 'message': 'The execution failed due to an exception.', 'data': 'Reverted'})
ms-kovan_1                    | Traceback (most recent call last):
ms-kovan_1                    |   File "/services/src/monitoring_service/handlers.py", line 479, in action_monitoring_triggered_event_handler
ms-kovan_1                    |     ).transact({"from": context.ms_state.address})
ms-kovan_1                    |   File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1151, in transact
ms-kovan_1                    |     **self.kwargs
ms-kovan_1                    |   File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1454, in transact_with_contract_function
ms-kovan_1                    |     txn_hash = web3.eth.sendTransaction(transact_transaction)
ms-kovan_1                    |   File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 264, in sendTransaction
ms-kovan_1                    |     get_buffered_gas_estimate(self.web3, transaction),
ms-kovan_1                    |   File "/usr/local/lib/python3.7/site-packages/web3/utils/transactions.py", line 84, in get_buffered_gas_estimate
ms-kovan_1                    |     gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
ms-kovan_1                    |   File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 305, in estimateGas
ms-kovan_1                    |     [transaction],
ms-kovan_1                    |   File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
ms-kovan_1                    |     raise ValueError(response["error"])
ms-kovan_1                    | ValueError: {'code': -32016, 'message': 'The execution failed due to an exception.', 'data': 'Reverted'}
```

and gets catched in the handler:
```py
    except Exception as exc:  # pylint: disable=broad-except
        log.error("Sending tx failed", exc_info=True, err=exc)
```

I wonder if we should remove the `exc_info=True` here.
