### ISSUE TITLE
Matrix startup times out

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#616]
I see a lot of logs like this on the deployed services.

```
ESC[36mpfs-goerli_1                  |ESC[0m Traceback (most recent call last):
ESC[36mpfs-goerli_1                  |ESC[0m   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
ESC[36mpfs-goerli_1                  |ESC[0m     "__main__", mod_spec)
ESC[36mpfs-goerli_1                  |ESC[0m   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
ESC[36mpfs-goerli_1                  |ESC[0m     exec(code, run_globals)
ESC[36mpfs-goerli_1                  |ESC[0m   File "/services/src/pathfinding_service/cli.py", line 122, in <module>
ESC[36mpfs-goerli_1                  |ESC[0m     main(auto_envvar_prefix="PFS")  # pragma: no cover
ESC[36mpfs-goerli_1                  |ESC[0m   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
ESC[36mpfs-goerli_1                  |ESC[0m     return self.main(*args, **kwargs)
ESC[36mpfs-goerli_1                  |ESC[0m   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
ESC[36mpfs-goerli_1                  |ESC[0m     rv = self.invoke(ctx)
ESC[36mpfs-goerli_1                  |ESC[0m   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
ESC[36mpfs-goerli_1                  |ESC[0m     return ctx.invoke(self.callback, **ctx.params)
ESC[36mpfs-goerli_1                  |ESC[0m   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
ESC[36mpfs-goerli_1                  |ESC[0m     return callback(*args, **kwargs)
ESC[36mpfs-goerli_1                  |ESC[0m   File "/services/src/raiden_libs/cli.py", line 183, in call_with_blockchain_info
ESC[36mpfs-goerli_1                  |ESC[0m     return callback(**params)
ESC[36mpfs-goerli_1                  |ESC[0m   File "/services/src/raiden_libs/cli.py", line 128, in call_with_common_options_initialized
ESC[36mpfs-goerli_1                  |ESC[0m     return func(**params)
ESC[36mpfs-goerli_1                  |ESC[0m   File "/services/src/pathfinding_service/cli.py", line 107, in main
ESC[36mpfs-goerli_1                  |ESC[0m     service.run()
ESC[36mpfs-goerli_1                  |ESC[0m   File "src/gevent/greenlet.py", line 718, in gevent._greenlet.Greenlet.run
ESC[36mpfs-goerli_1                  |ESC[0m   File "src/gevent/greenlet.py", line 706, in gevent._greenlet.Greenlet._report_error
ESC[36mpfs-goerli_1                  |ESC[0m   File "/services/src/raiden_libs/gevent_error_handler.py", line 24, in error_handler
ESC[36mpfs-goerli_1                  |ESC[0m     Hub.handle_system_error(self, etype, value)
ESC[36mpfs-goerli_1                  |ESC[0m   File "/usr/local/lib/python3.7/site-packages/gevent/hub.py", line 488, in handle_system_error
ESC[36mpfs-goerli_1                  |ESC[0m     self.parent.throw(type, value)
ESC[36mpfs-goerli_1                  |ESC[0m AssertionError: MatrixListener did not start in time.
```

A quick fix in done in #615. However, ideally we should find out what takes so long. A first guess is the joining of all broadcasting rooms.

**Comment by palango** [comment]
So #615 didn't fix the issue.

All matrix servers are reachable from the deployment server:
```sh
# ping transport01.raiden.network
PING transport01.raiden.network (159.203.40.123) 56(84) bytes of data.
64 bytes from transport01.raiden.network (159.203.40.123): icmp_seq=1 ttl=57 time=94.2 ms
64 bytes from transport01.raiden.network (159.203.40.123): icmp_seq=2 ttl=57 time=92.9 ms
^C
--- transport01.raiden.network ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 92.917/93.607/94.298/0.755 ms
# ping transport02.raiden.network
PING transport02.raiden.network (206.189.41.93) 56(84) bytes of data.
64 bytes from transport02.raiden.network (206.189.41.93): icmp_seq=1 ttl=58 time=175 ms
64 bytes from transport02.raiden.network (206.189.41.93): icmp_seq=2 ttl=58 time=174 ms
64 bytes from transport02.raiden.network (206.189.41.93): icmp_seq=3 ttl=58 time=174 ms
^C
--- transport02.raiden.network ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 174.635/174.960/175.596/0.564 ms
# ping transport03.raiden.network
PING transport03.raiden.network (139.59.3.95) 56(84) bytes of data.
64 bytes from transport03.raiden.network (139.59.3.95): icmp_seq=1 ttl=55 time=152 ms
64 bytes from transport03.raiden.network (139.59.3.95): icmp_seq=2 ttl=55 time=151 ms
^C
--- transport03.raiden.network ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 151.852/152.389/152.926/0.537 ms
# ping transport04.raiden.network
PING transport04.raiden.network (165.22.196.222) 56(84) bytes of data.
64 bytes from transport04.raiden.network (165.22.196.222): icmp_seq=1 ttl=61 time=1.86 ms
64 bytes from transport04.raiden.network (165.22.196.222): icmp_seq=2 ttl=61 time=0.560 ms
64 bytes from transport04.raiden.network (165.22.196.222): icmp_seq=3 ttl=61 time=0.548 ms
64 bytes from transport04.raiden.network (165.22.196.222): icmp_seq=4 ttl=61 time=0.520 ms
64 bytes from transport04.raiden.network (165.22.196.222): icmp_seq=5 ttl=61 time=0.492 ms
64 bytes from transport04.raiden.network (165.22.196.222): icmp_seq=6 ttl=61 time=0.603 ms
64 bytes from transport04.raiden.network (165.22.196.222): icmp_seq=7 ttl=61 time=0.375 ms
64 bytes from transport04.raiden.network (165.22.196.222): icmp_seq=8 ttl=61 time=0.523 ms
64 bytes from transport04.raiden.network (165.22.196.222): icmp_seq=9 ttl=61 time=0.465 ms
^C
--- transport04.raiden.network ping statistics ---
9 packets transmitted, 9 received, 0% packet loss, time 8153ms
rtt min/avg/max/mdev = 0.375/0.661/1.865/0.430 ms
```

**Comment by palango** [comment]
The issue is that the requests to matrix are rate limited.

```
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
pfs-goerli_1                  | https://transport04.raiden.network:443 "POST /_matrix/client/r0/login HTTP/1.1" 429 79
```

This probably is because all services are started at the same time.

**Comment by LefterisJP** [comment]
@palango this is now fixed, right?

**Comment by palango** [comment]
> @palango this is now fixed, right?

It should be. But we have to see if #618 was enough to fix it in the future. I'll monitor it.

**Comment by palango** [comment]
This still happens after automatic deployments

**Comment by palango** [comment]
Seems like this was related to a OOM of the transport server
