### ISSUE TITLE
can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden-services#660]
## Problem Definition

Looking at the PFS goerli-with-fee, i can see that it was crashing with the following exception:

```
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]: {"message": {"signature": "0x3dae038435e01e80611c49a0637ca9e42c592792ca8d153ac729499814d1fe485e56ba52e6f53fc59ed83d85dd10cec7c98a83b0916650536c151cde2d45b5251c", "canonical_identifier": {"ch
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]: {"message": {"signature": "0x90e2f016f66e6fb9c38b149b03e86f1db8c4800afc5d4ec9ba14442de86a57075bfa40c420513eb4c63a39d4449d5c864802599eb7712bf12c5b619aecc99ae21b", "canonical_identifier": {"ch
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]: {"event": "Unhandled exception. Terminating the program...Please report this issue at https://github.com/raiden-network/raiden-services/issues", "level": "critical", "logger": "raiden_libs.g
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]: {"event": "Unhandled exception. Terminating the program...Please report this issue at https://github.com/raiden-network/raiden-services/issues", "level": "critical", "logger": "raiden_libs.g
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]: {"event": "Stopping Pathfinding Service...", "level": "info", "logger": "__main__", "timestamp": "2019-11-26 02:25:29.371709"}
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]: Traceback (most recent call last):
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     "__main__", mod_spec)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     exec(code, run_globals)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/services/src/pathfinding_service/cli.py", line 130, in <module>
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     main(auto_envvar_prefix="PFS")  # pragma: no cover
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     return self.main(*args, **kwargs)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     rv = self.invoke(ctx)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     return ctx.invoke(self.callback, **ctx.params)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     return callback(*args, **kwargs)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/services/src/raiden_libs/cli.py", line 183, in call_with_blockchain_info
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     return callback(**params)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/services/src/raiden_libs/cli.py", line 128, in call_with_common_options_initialized
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     return func(**params)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/services/src/pathfinding_service/cli.py", line 115, in main
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     service.run()
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "src/gevent/greenlet.py", line 718, in gevent._greenlet.Greenlet.run
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "src/gevent/greenlet.py", line 706, in gevent._greenlet.Greenlet._report_error
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/services/src/raiden_libs/gevent_error_handler.py", line 24, in error_handler
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     Hub.handle_system_error(self, etype, value)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/gevent/hub.py", line 488, in handle_system_error
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]:     self.parent.throw(type, value)
Nov 26 02:25:29 services-dev e8e174bcfd67[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by palango** [comment]
Unfortunate the stacktrace is missing valuable information, next time this occurs we should have better information thanks to https://github.com/raiden-network/raiden-services/pull/652

Checking this led me to improve the PFS Fee update tests in https://github.com/raiden-network/raiden-services/pull/661

**Comment by palango** [comment]
This happened multiple times:
```
Nov 26 02:25:29 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:26:09 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:26:32 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:26:55 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:27:19 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:27:42 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:28:09 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:28:34 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:28:56 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:29:20 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:29:43 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:30:09 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:30:33 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:30:59 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:31:23 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 02:31:47 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 03:36:19 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 03:36:45 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 03:37:09 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 03:37:33 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 03:37:56 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 03:38:20 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 03:38:45 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 08:18:07 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by palango** [comment]
Got a better stacktrace:
```
pfs-goerli-with-fee_1         | Traceback (most recent call last):
pfs-goerli-with-fee_1         |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
pfs-goerli-with-fee_1         |     "__main__", mod_spec)
pfs-goerli-with-fee_1         |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
pfs-goerli-with-fee_1         |     exec(code, run_globals)
pfs-goerli-with-fee_1         |   File "/services/src/pathfinding_service/cli.py", line 130, in <module>
pfs-goerli-with-fee_1         |     main(auto_envvar_prefix="PFS")  # pragma: no cover
pfs-goerli-with-fee_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
pfs-goerli-with-fee_1         |     return self.main(*args, **kwargs)
pfs-goerli-with-fee_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
pfs-goerli-with-fee_1         |     rv = self.invoke(ctx)
pfs-goerli-with-fee_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
pfs-goerli-with-fee_1         |     return ctx.invoke(self.callback, **ctx.params)
pfs-goerli-with-fee_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
pfs-goerli-with-fee_1         |     return callback(*args, **kwargs)
pfs-goerli-with-fee_1         |   File "/services/src/raiden_libs/cli.py", line 221, in call_with_blockchain_info
pfs-goerli-with-fee_1         |     return callback(**params)
pfs-goerli-with-fee_1         |   File "/services/src/raiden_libs/cli.py", line 164, in call_with_common_options_initialized
pfs-goerli-with-fee_1         |     return func(**params)
pfs-goerli-with-fee_1         |   File "/services/src/pathfinding_service/cli.py", line 102, in main
pfs-goerli-with-fee_1         |     matrix_servers=matrix_server,
pfs-goerli-with-fee_1         |   File "/services/src/pathfinding_service/service.py", line 108, in __init__
pfs-goerli-with-fee_1         |     self.token_networks = self._load_token_networks()
pfs-goerli-with-fee_1         |   File "/services/src/pathfinding_service/service.py", line 113, in _load_token_networks
pfs-goerli-with-fee_1         |     for channel in self.database.get_channels():
pfs-goerli-with-fee_1         |   File "/services/src/pathfinding_service/database.py", line 169, in get_channels
pfs-goerli-with-fee_1         |     yield Channel.Schema().load(channel_dict)
pfs-goerli-with-fee_1         |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 714, in load
pfs-goerli-with-fee_1         |     data, many=many, partial=partial, unknown=unknown, postprocess=True
pfs-goerli-with-fee_1         |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 892, in _do_load
pfs-goerli-with-fee_1         |     raise exc
pfs-goerli-with-fee_1         | marshmallow.exceptions.ValidationError: {'fee_schedule2': {'timestamp': ['Not a valid naive datetime.']}, 'fee_schedule1': {'timestamp': ['Not a valid naive datetime.']}}
```

**Comment by palango** [comment]
I think https://github.com/raiden-network/raiden-services/pull/661/files#diff-9d834d394a17c82a987290690d6360bbR27 might have fixed that.

**Comment by palango** [comment]
This didn't happen again after above changes.
