### ISSUE TITLE
GMatrixClient.message_worker failed with TypeError

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#717]
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 614, in _handle_message
    self._handle_responses(currently_queued_responses)
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 694, in _handle_responses
    self.handle_messages_callback(all_messages)
  File "/Users/paul/Projects/brainbot/raiden-services/src/raiden_libs/matrix.py", line 253, in _handle_matrix_sync
    all_messages.extend(self._handle_message(room, text))
  File "/Users/paul/Projects/brainbot/raiden-services/src/raiden_libs/matrix.py", line 298, in _handle_message
    data=data, peer_address=peer_address, rate_limiter=self._rate_limiter
  File "/Users/paul/Projects/brainbot/raiden-services/src/raiden_libs/matrix.py", line 105, in deserialize_messages
    message = MessageSerializer.deserialize(line)
  File "/Users/paul/Projects/brainbot/raiden-services/venv/lib/python3.7/site-packages/raiden/storage/serialization/serializer.py", line 132, in deserialize
    msg_type = decoded_json.pop("type")
TypeError: 'str' object cannot be interpreted as an integer
2020-02-05T15:21:24Z <Greenlet "GMatrixClient.message_worker user_id:@0xbf1dabcf9eca2d89fb24be3e6e45ef422ec39ca0:transport01.raiden.network" at 0x10bab34d0: <bound method GMatrixClient._handle_message of <raiden.network.transport.matrix.client.GMatrixClient object at 0x10bb8f5d0>>(NotifyingQueue(num_items=1), <gevent._event.Event object at 0x10cc0c980>)> failed with TypeError
```

Ref https://sentry.io/organizations/raiden-network/issues/1497342442/?project=1509055&query=is%3Aunresolved

**Comment by karlb** [comment]
`decoded_json` is probably a list. At least that would cause exactly this error:
```python
>>> [1, 2].pop('type')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object cannot be interpreted as an integer

```
