### ISSUE TITLE
The User instance provided to validate_userid_signature must have the displayname attribute set

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#733]
```
AssertionError: The User instance provided to validate_userid_signature must have the displayname attribute set. Make sure to warm the value using the DisplayNameCache.
(28 additional frame(s) were not displayed)
...
  File "raiden/network/transport/matrix/client.py", line 748, in _handle_responses
    callback(presence_update, next(self._presence_update_ids))
  File "raiden/network/transport/matrix/utils.py", line 397, in _presence_listener
    address = self._validate_userid_signature(user)
  File "raiden/network/transport/matrix/utils.py", line 473, in _validate_userid_signature
    return validate_userid_signature(user)
  File "__init__.py", line 60, in wrapper
    v = func(*args, **kwargs)
  File "raiden/network/transport/matrix/utils.py", line 697, in validate_userid_signature
    assert displayname is not None, msg
```

See https://sentry.io/share/issue/fe1263afbc21440eb29c86ed9477c844/

**Comment by palango** [comment]
Happened again tonight, coinciding with a full disk at the transport servers:

```
pfs-goerli_1                  | 2020-03-11T09:39:43Z <MatrixListener at 0x7f365691d290: _run> failed with AssertionError
pfs-goerli_1                  | Traceback (most recent call last):
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
  "__main__", mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
  exec(code, run_globals)
File "/services/src/pathfinding_service/cli.py", line 138, in <module>
  main(auto_envvar_prefix="PFS")  # pragma: no cover
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
  return self.main(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
  rv = self.invoke(ctx)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
  return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
  return callback(*args, **kwargs)
File "/services/src/raiden_libs/cli.py", line 221, in call_with_blockchain_info
  return callback(**params)
File "/services/src/raiden_libs/cli.py", line 164, in call_with_common_options_initialized
  return func(**params)
File "/services/src/pathfinding_service/cli.py", line 108, in main
  service.startup_finished.get(timeout=60)
File "src/gevent/event.py", line 279, in gevent._event.AsyncResult.get
File "src/gevent/event.py", line 307, in gevent._event.AsyncResult.get
File "src/gevent/event.py", line 297, in gevent._event.AsyncResult.get
File "src/gevent/event.py", line 277, in gevent._event.AsyncResult._raise_exception
File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
  raise value.with_traceback(tb)
File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
File "/services/src/raiden_libs/matrix.py", line 199, in _run
  self._client.stop_listener_thread()
File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 487, in stop_listener_thread
  {self.message_worker}, timeout=SHUTDOWN_TIMEOUT, raise_error=True
File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall
File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall
File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
  raise value.with_traceback(tb)
File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 713, in _handle_message
  self._handle_responses(currently_queued_responses)
File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 748, in _handle_responses
  callback(presence_update, next(self._presence_update_ids))
File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 397, in _presence_listener
  address = self._validate_userid_signature(user)
File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 473, in _validate_userid_signature
  return validate_userid_signature(user)
File "/usr/local/lib/python3.7/site-packages/cachetools/__init__.py", line 60, in wrapper
  v = func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 697, in validate_userid_signature
  assert displayname is not None, msg
pfs-goerli_1                  | AssertionError: The User instance provided to validate_userid_signature must have the displayname attribute set. Make sure to warm the value using the DisplayNameCache.
```

In the chat we agreed that we should not silently return in this code in `DisplayNameCache.warm_users()`:
```py
                    try:
                        user.get_display_name()
                    except MatrixRequestError:
                        return
```
