### ISSUE TITLE
Handle matrix errors better

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#799]
## Proposed Solution
- [ ] Fix this particular instance of the problem using the stacktrace - catch the exception and set node offline in the pfs
- [ ] Turn of retries of get_display_name
- [ ] Create a follow up issue for the highly complex underlying root cause 

## The Problem
We had an incident with PFSs crashing because matrix calls threw errors. These errors persisted and made it impossible for the PFS to restart.

We should gracefully handle that situation and not crash, but retry the call to matrix later.

```
Traceback (most recent call last):
  File "/Users/paul/Projects/brainbot/raiden-services/src/pathfinding_service/service.py", line 139, in _run
    self.matrix_listener.startup_finished.get(timeout=MATRIX_START_TIMEOUT)
  File "src/gevent/event.py", line 279, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 304, in gevent._event.AsyncResult.get
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.timeout.Timeout: 30 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden-services/src/pathfinding_service/service.py", line 141, in _run
    raise Exception("MatrixListener did not start in time.")
Exception: MatrixListener did not start in time.
2020-06-10T09:10:13Z <PathfindingService at 0x109d24830: _run> failed with Exception
```

The failing calls were to `get_display_name`:
```
2020-06-10 09:09:49.148879 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixRequestError('502: {"errcode":"M_UNKNOWN","error":"Failed to fetch profile"}') wait_for=5.0
2020-06-10 09:09:54.225403 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixRequestError('502: {"errcode":"M_UNKNOWN","error":"Failed to fetch profile"}') wait_for=10.0
2020-06-10 09:10:04.304672 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixRequestError('502: {"errcode":"M_UNKNOWN","error":"Failed to fetch profile"}') wait_for=20.0
```

**Comment by karlb** [comment]
Restarting doesn't sound too bad to me, since it allows the PFS to recover from a variety of problems (e.g. by choosing a different matrix server).

If it can't connect to matrix at all, being down at least provides a clear error condition instead of taking fees while providing routes based on outdated availabilities and capacities.

**Comment by palango** [comment]
> (e.g. by choosing a different matrix server).

This doesn't work as we bind the MSRC and PFS to the matrix server of the bundle: https://github.com/raiden-network/raiden-service-bundle/blob/master/docker-compose.yml#L39

> If it can't connect to matrix at all, being down at least provides a clear error condition instead of taking fees while providing routes based on outdated availabilities and capacities.

In general I agree, but yesterday all of the PFS on mainnet when down because of one faulty matrix server, so this is a case that we should handle better.

**Comment by konradkonrad** [comment]
I could trigger a similar issue by spamming a matrix server with PFS restarts:
```
2020-06-18 15:36:04.880699 [debug    ] Tracking address               [raiden_libs.matrix] address=0xF128A427DeFf3a4f792373f4BE38bEecD07d4ffE current_presence=<AddressReachability.UNKNOWN: 3> refresh=False
2020-06-18 15:36:04.880796 [debug    ] Waiting for service to start before accepting API requests [pathfinding_service.cli] 
2020-06-18 15:36:05.029577 [debug    ] Logged in                      [raiden.network.transport.matrix.utils] homeserver=transport.mainnet.raiden.anyblock.tools node=0x01C256B11232260a12aDf902298c96A30B1fbD1F server_url=https://transport.mainnet.raiden.anyblock.tools
2020-06-18 15:36:06.671234 [debug    ] Sync filter created            [raiden.network.transport.matrix.client] filter={'presence': {'types': ['m.presence']}, 'account_data': {'not_types': ['*']}, 'room': {'ephemeral': {'not_types': ['m.receipt']}, 'rooms': ['!hHfcOsOoWgCQGeVUQQ:transport.mainnet.raiden.anyblock.tools']}} filter_id=0
2020-06-18 15:36:06.671429 [debug    ] Sync called                    [raiden.network.transport.matrix.client] last_sync_time=inf node=0x01c256b11232260a12adf902298c96a30b1fbd1f sync_filter_id=0 sync_iteration=0 user_id=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools
2020-06-18 15:36:06.671524 [debug    ] Calling api.sync               [raiden.network.transport.matrix.client] node=0x01c256b11232260a12adf902298c96a30b1fbd1f sync_iteration=0 time_since_last_sync_in_seconds=-inf user_id=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools
2020-06-18 15:36:09.116057 [debug    ] api.sync returned              [raiden.network.transport.matrix.client] node=0x01c256b11232260a12adf902298c96a30b1fbd1f sync_iteration=0 time_after_sync=366770.322309039 time_taken=2.4445014800294302 user_id=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools
2020-06-18 15:36:09.116267 [debug    ] Sync returned                  [raiden.network.transport.matrix.client] current_user=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools elapsed=2.4445014800294302 node=0x01c256b11232260a12adf902298c96a30b1fbd1f presence_events_qty=11 rooms_invited_member_count=0 rooms_invites_qty=0 rooms_join_account_data_events_qty=0 rooms_join_ephemeral_events_qty=0 rooms_join_state_events_qty=14209 rooms_join_state_qty=1 rooms_join_timeline_events_qty=10 rooms_joined_member_count=0 rooms_leaves_qty=0 to_device_events_qty=0 token=UUID('3a29d140-3c37-49f0-957a-bcb51d3c270a')
2020-06-18 15:36:09.116444 [debug    ] Sync called                    [raiden.network.transport.matrix.client] last_sync_time=366767.877807559 node=0x01c256b11232260a12adf902298c96a30b1fbd1f sync_filter_id=0 sync_iteration=1 user_id=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools
2020-06-18 15:36:09.116540 [debug    ] Calling api.sync               [raiden.network.transport.matrix.client] node=0x01c256b11232260a12adf902298c96a30b1fbd1f sync_iteration=1 time_since_last_sync_in_seconds=2.445015008037444 user_id=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools
2020-06-18 15:36:09.118136 [debug    ] Handling Matrix response       [raiden.network.transport.matrix.client] current_size=1 node=0x01c256b11232260a12adf902298c96a30b1fbd1f processing_lag=datetime.timedelta(microseconds=1729) token=UUID('3a29d140-3c37-49f0-957a-bcb51d3c270a')
2020-06-18 15:36:09.219613 [debug    ] Changing user presence state   [raiden.network.transport.matrix.utils] current_user=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools node=0x01c256b11232260a12adf902298c96a30b1fbd1f prev_state=None state=<UserPresence.UNAVAILABLE: 'unavailable'> user_id=@0xf128a427deff3a4f792373f4be38beecd07d4ffe:transport.mainnet.raiden.anyblock.tools
2020-06-18 15:36:09.219843 [debug    ] Changing address reachability state [raiden.network.transport.matrix.utils] address=0xF128A427DeFf3a4f792373f4BE38bEecD07d4ffE change_after=datetime.timedelta(days=18431, seconds=63369, microseconds=219746) current_user=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools last_change=datetime.datetime(1970, 1, 1, 0, 0) node=0x01c256b11232260a12adf902298c96a30b1fbd1f prev_state=<AddressReachability.UNKNOWN: 3> state=<AddressReachability.REACHABLE: 1>
2020-06-18 15:36:09.256705 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixRequestError('503: {"errcode":"M_UNKNOWN","error":"Service Unavailable"}') wait_for=5.0
2020-06-18 15:36:14.300284 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixRequestError('503: {"errcode":"M_UNKNOWN","error":"Service Unavailable"}') wait_for=10.0
2020-06-18 15:36:24.407283 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixRequestError('503: {"errcode":"M_UNKNOWN","error":"Service Unavailable"}') wait_for=20.0
2020-06-18 15:36:34.463628 [debug    ] api.sync returned              [raiden.network.transport.matrix.client] node=0x01c256b11232260a12adf902298c96a30b1fbd1f sync_iteration=1 time_after_sync=366795.669893654 time_taken=25.347071086987853 user_id=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools
2020-06-18 15:36:34.463806 [debug    ] Sync returned                  [raiden.network.transport.matrix.client] current_user=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools elapsed=25.347071086987853 node=0x01c256b11232260a12adf902298c96a30b1fbd1f presence_events_qty=1 rooms_invited_member_count=0 rooms_invites_qty=0 rooms_join_account_data_events_qty=0 rooms_join_ephemeral_events_qty=0 rooms_join_state_events_qty=0 rooms_join_state_qty=0 rooms_join_timeline_events_qty=0 rooms_joined_member_count=0 rooms_leaves_qty=0 to_device_events_qty=0 token=UUID('40d77fae-8675-4de9-84cf-5eab25beca72')
2020-06-18 15:36:34.463939 [debug    ] Sync called                    [raiden.network.transport.matrix.client] last_sync_time=366770.322822567 node=0x01c256b11232260a12adf902298c96a30b1fbd1f sync_filter_id=0 sync_iteration=2 user_id=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools
2020-06-18 15:36:34.464025 [debug    ] Calling api.sync               [raiden.network.transport.matrix.client] node=0x01c256b11232260a12adf902298c96a30b1fbd1f sync_iteration=2 time_since_last_sync_in_seconds=25.347484804980922 user_id=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools
Traceback (most recent call last):
  File "/home/konrad/Projects/raiden-services/src/pathfinding_service/service.py", line 132, in _run
    self.matrix_listener.startup_finished.get(timeout=MATRIX_START_TIMEOUT)
  File "src/gevent/event.py", line 279, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 304, in gevent._event.AsyncResult.get
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.timeout.Timeout: 30 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/konrad/Projects/raiden-services/src/pathfinding_service/service.py", line 134, in _run
    raise Exception("MatrixListener did not start in time.")
Exception: MatrixListener did not start in time.
2020-06-18T15:36:34Z <PathfindingService at 0x7fc1b2da83b0: _run> failed with Exception

2020-06-18 15:36:46.543456 [debug    ] Changing user presence state   [raiden.network.transport.matrix.utils] current_user=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools node=0x01c256b11232260a12adf902298c96a30b1fbd1f prev_state=None state=<UserPresence.UNAVAILABLE: 'unavailable'> user_id=@0x95b2485da3186337dad276e7a96799bddf00c168:transport.raiden.dappnode.io
2020-06-18 15:36:46.543718 [debug    ] Changing address reachability state [raiden.network.transport.matrix.utils] address=0x95b2485Da3186337dAD276e7A96799bddF00C168 change_after=datetime.timedelta(days=18431, seconds=63406, microseconds=543594) current_user=@0x01c256b11232260a12adf902298c96a30b1fbd1f:transport.mainnet.raiden.anyblock.tools last_change=datetime.datetime(1970, 1, 1, 0, 0) node=0x01c256b11232260a12adf902298c96a30b1fbd1f prev_state=<AddressReachability.UNKNOWN: 3> state=<AddressReachability.REACHABLE: 1>
```
